FROM xosproject/alpine-grpc-base:0.9.0

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt \
 && pip freeze > /var/xos/pip_freeze_simpleexampleservice_service_`date -u +%Y%m%dT%H%M%S`

COPY xos/synchronizer /opt/xos/synchronizers/hello-world
COPY VERSION /opt/xos/synchronizers/hello-world/

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/hello-world"

CMD ["/usr/bin/python", "/opt/xos/synchronizers/hello-world/hello-world-synchronizer.py"]

